import React,{useEffect,useMemo,useState} from 'react'
import {supabase} from './supabase'
import JsBarcode from 'jsbarcode'
import * as XLSX from 'xlsx'
const DAYS=['ראשון','שני','שלישי','רביעי','חמישי','שישי','שבת']
const ACTIVE_STATUSES=['pending_destruction','pending_whatsapp','whatsapp_sent','waiting_agent','approved','scheduled_pickup']
export default function MasterData(){
 const [companies,setCompanies]=useState([]),[agents,setAgents]=useState([]),[locations,setLocations]=useState([]),[products,setProducts]=useState([]),[tab,setTab]=useState('companies')
 const [f,setF]=useState({name:'',return_method:'whatsapp',agent_day:'',shipping_day:'',returns_policy:'',special_instructions:''})
 async function load(){const [c,a,l,p]=await Promise.all([supabase.from('companies').select('*').order('name'),supabase.from('agents').select('*').order('name'),supabase.from('storage_locations').select('*').order('shelf'),supabase.from('products').select('*').order('created_at',{ascending:false})]);if(!c.error)setCompanies(c.data||[]);if(!a.error)setAgents(a.data||[]);if(!l.error)setLocations(l.data||[]);if(!p.error)setProducts(p.data||[])}
 useEffect(()=>{load()},[])
 async function add(e){e.preventDefault();const row={...f,agent_day:f.agent_day===''?null:Number(f.agent_day),shipping_day:f.shipping_day===''?null:Number(f.shipping_day)};const {error}=await supabase.from('companies').insert(row);if(error)return alert(error.message);setF({name:'',return_method:'whatsapp',agent_day:'',shipping_day:'',returns_policy:'',special_instructions:''});load()}
 const grouped=useMemo(()=>{const map={};for(const c of companies)map[c.id]={company:c,rows:[]};for(const p of products){if(!p.company_id||!ACTIVE_STATUSES.includes(p.status))continue;if(!map[p.company_id])map[p.company_id]={company:{id:p.company_id,name:p.supplier||'ללא שם'},rows:[]};map[p.company_id].rows.push(p)}return Object.values(map).map(g=>{const byCode={};for(const p of g.rows){const code=p.sku||'ללא קוד';if(!byCode[code])byCode[code]={code,name:p.name||'',qty:0,rows:[]};byCode[code].qty+=Number(p.qty)||0;byCode[code].rows.push(p)}return {...g,items:Object.values(byCode)}}).filter(g=>g.items.length)},[companies,products])
 function exportExcel(group){const rows=group.items.map(x=>({'קוד פריט':x.code,'שם מוצר':x.name,'כמות':x.qty}));const ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=[{wch:22},{wch:34},{wch:10}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'החזרות');XLSX.writeFile(wb,`${group.company.name}-החזרות.xlsx`)}
 function barcodeSheet(group){const win=window.open('','_blank');if(!win)return alert('הדפדפן חסם חלון חדש');win.document.write(`<html dir="rtl"><head><title>${group.company.name} - ברקודים</title><style>body{font-family:Arial;padding:24px}h1{margin-bottom:20px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.item{border:1px solid #ddd;border-radius:12px;padding:14px;page-break-inside:avoid}.name{font-weight:700;margin-bottom:6px}.qty{font-size:14px;margin-top:4px}@media print{button{display:none}.grid{grid-template-columns:repeat(2,1fr)}}</style></head><body><button onclick="window.print()">הדפס / שמור PDF</button><h1>${group.company.name}</h1><div class="grid" id="grid"></div></body></html>`);const grid=win.document.getElementById('grid');for(const item of group.items){const box=win.document.createElement('div');box.className='item';const name=win.document.createElement('div');name.className='name';name.textContent=item.name;const svg=win.document.createElementNS('http://www.w3.org/2000/svg','svg');const qty=win.document.createElement('div');qty.className='qty';qty.textContent=`כמות: ${item.qty}`;box.append(name,svg,qty);grid.appendChild(box);try{JsBarcode(svg,String(item.code),{format:'CODE128',displayValue:true,height:58,width:2,margin:6})}catch{svg.outerHTML=`<div>${item.code}</div>`}}win.document.close()}
 async function renameItem(item){const next=prompt('שם חדש לברקוד',item.name);if(!next||next===item.name)return;const ids=item.rows.map(r=>r.id);const {error}=await supabase.from('products').update({name:next}).in('id',ids);if(error)return alert(error.message);await supabase.from('product_catalog').update({product_name:next}).eq('barcode',item.code);load()}
 return <div className="page"><div className="toolbar"><div><h1>הגדרות המחסן</h1><p>המידע כאן קובע איך המערכת תשבץ החזרה אוטומטית.</p></div></div><div className="masterTabs">{[['companies','חברות'],['rubrics','רובריקות חברות'],['agents','סוכנים'],['locations','מדפים וקופסאות']].map(([id,n])=><button key={id} className={`btn ${tab===id?'primary':'ghost'}`} onClick={()=>setTab(id)}>{n}</button>)}</div>
 {tab==='companies'&&<><section className="card"><h2>הוסף חברה</h2><form className="formGrid" onSubmit={add}><label>שם<input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>שיטת טיפול<select value={f.return_method} onChange={e=>setF({...f,return_method:e.target.value})}><option value="whatsapp">WhatsApp / ללא סוכן</option><option value="agent">באמצעות סוכן</option><option value="none">לא הוגדר</option></select></label><label>יום סוכן<select value={f.agent_day} onChange={e=>setF({...f,agent_day:e.target.value})}><option value="">לא הוגדר</option>{DAYS.map((d,i)=><option value={i} key={d}>יום {d}</option>)}</select></label><label>יום משלוח<select value={f.shipping_day} onChange={e=>setF({...f,shipping_day:e.target.value})}><option value="">לא הוגדר</option>{DAYS.map((d,i)=><option value={i} key={d}>יום {d}</option>)}</select></label><label>מדיניות החזרות<input value={f.returns_policy} onChange={e=>setF({...f,returns_policy:e.target.value})}/></label><label>הוראות מיוחדות<input value={f.special_instructions} onChange={e=>setF({...f,special_instructions:e.target.value})}/></label><div className="full"><button className="btn primary">שמור חברה</button></div></form></section><section className="card"><table><thead><tr><th>חברה</th><th>טיפול</th><th>יום סוכן</th><th>יום משלוח</th></tr></thead><tbody>{companies.map(c=><tr key={c.id}><td>{c.name}</td><td>{c.return_method}</td><td>{c.agent_day==null?'—':DAYS[c.agent_day]}</td><td>{c.shipping_day==null?'—':DAYS[c.shipping_day]}</td></tr>)}</tbody></table></section></>}
 {tab==='rubrics'&&<div style={{display:'grid',gap:18}}>{grouped.length===0?<section className="card"><div className="empty">אין כרגע פריטים פעילים שמקושרים לחברות</div></section>:grouped.map(g=><section className="card" key={g.company.id}><div className="sectionTitle"><div><h2>{g.company.name}</h2><div className="muted">{g.items.reduce((s,x)=>s+x.qty,0)} יחידות • {g.items.length} קודי פריט</div></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn ghost" onClick={()=>barcodeSheet(g)}>תמונת / דף ברקודים</button><button className="btn primary" onClick={()=>exportExcel(g)}>ייצוא Excel</button></div></div><div className="tableWrap"><table><thead><tr><th>קוד פריט / ברקוד</th><th>שם</th><th>כמות</th><th></th></tr></thead><tbody>{g.items.map(item=><tr key={item.code}><td>{item.code}</td><td><b>{item.name}</b></td><td>{item.qty}</td><td><button className="btn small" onClick={()=>renameItem(item)}>ערוך שם</button></td></tr>)}</tbody></table></div></section>)}</div>}
 {tab==='agents'&&<section className="card"><table><thead><tr><th>סוכן</th><th>חברה</th><th>טלפון</th><th>יום</th></tr></thead><tbody>{agents.map(a=><tr key={a.id}><td>{a.name}</td><td>{companies.find(c=>c.id===a.company_id)?.name||'—'}</td><td>{a.phone||'—'}</td><td>{a.arrival_day==null?'—':DAYS[a.arrival_day]}</td></tr>)}</tbody></table></section>}
 {tab==='locations'&&<section className="card"><table><thead><tr><th>חברה</th><th>מדף</th><th>קופסה</th></tr></thead><tbody>{locations.map(l=><tr key={l.id}><td>{companies.find(c=>c.id===l.company_id)?.name||'—'}</td><td>{l.shelf}</td><td>{l.box_name}</td></tr>)}</tbody></table></section>}</div>
}