import React,{useEffect,useState} from 'react'
import {supabase} from './supabase'
const DAYS=['ראשון','שני','שלישי','רביעי','חמישי','שישי','שבת']
export default function MasterData(){
 const [companies,setCompanies]=useState([]),[agents,setAgents]=useState([]),[locations,setLocations]=useState([]),[tab,setTab]=useState('companies')
 const [f,setF]=useState({name:'',return_method:'whatsapp',agent_day:'',shipping_day:'',returns_policy:'',special_instructions:''})
 async function load(){const [c,a,l]=await Promise.all([supabase.from('companies').select('*').order('name'),supabase.from('agents').select('*').order('name'),supabase.from('storage_locations').select('*').order('shelf')]);if(!c.error)setCompanies(c.data||[]);if(!a.error)setAgents(a.data||[]);if(!l.error)setLocations(l.data||[])}
 useEffect(()=>{load()},[])
 async function add(e){e.preventDefault();const row={...f,agent_day:f.agent_day===''?null:Number(f.agent_day),shipping_day:f.shipping_day===''?null:Number(f.shipping_day)};const {error}=await supabase.from('companies').insert(row);if(error)return alert(error.message);setF({name:'',return_method:'whatsapp',agent_day:'',shipping_day:'',returns_policy:'',special_instructions:''});load()}
 return <div className="page"><div className="toolbar"><div><h1>הגדרות המחסן</h1><p>המידע כאן קובע איך המערכת תשבץ החזרה אוטומטית.</p></div></div><div className="masterTabs">{[['companies','חברות'],['agents','סוכנים'],['locations','מדפים וקופסאות']].map(([id,n])=><button key={id} className={`btn ${tab===id?'primary':'ghost'}`} onClick={()=>setTab(id)}>{n}</button>)}</div>
 {tab==='companies'&&<><section className="card"><h2>הוסף חברה</h2><form className="formGrid" onSubmit={add}><label>שם<input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>שיטת טיפול<select value={f.return_method} onChange={e=>setF({...f,return_method:e.target.value})}><option value="whatsapp">WhatsApp / ללא סוכן</option><option value="agent">באמצעות סוכן</option><option value="none">לא הוגדר</option></select></label><label>יום סוכן<select value={f.agent_day} onChange={e=>setF({...f,agent_day:e.target.value})}><option value="">לא הוגדר</option>{DAYS.map((d,i)=><option value={i} key={d}>יום {d}</option>)}</select></label><label>יום משלוח<select value={f.shipping_day} onChange={e=>setF({...f,shipping_day:e.target.value})}><option value="">לא הוגדר</option>{DAYS.map((d,i)=><option value={i} key={d}>יום {d}</option>)}</select></label><label>מדיניות החזרות<input value={f.returns_policy} onChange={e=>setF({...f,returns_policy:e.target.value})}/></label><label>הוראות מיוחדות<input value={f.special_instructions} onChange={e=>setF({...f,special_instructions:e.target.value})}/></label><div className="full"><button className="btn primary">שמור חברה</button></div></form></section><section className="card"><table><thead><tr><th>חברה</th><th>טיפול</th><th>יום סוכן</th><th>יום משלוח</th></tr></thead><tbody>{companies.map(c=><tr key={c.id}><td>{c.name}</td><td>{c.return_method}</td><td>{c.agent_day==null?'—':DAYS[c.agent_day]}</td><td>{c.shipping_day==null?'—':DAYS[c.shipping_day]}</td></tr>)}</tbody></table></section></>}
 {tab==='agents'&&<section className="card"><table><thead><tr><th>סוכן</th><th>חברה</th><th>טלפון</th><th>יום</th></tr></thead><tbody>{agents.map(a=><tr key={a.id}><td>{a.name}</td><td>{companies.find(c=>c.id===a.company_id)?.name||'—'}</td><td>{a.phone||'—'}</td><td>{a.arrival_day==null?'—':DAYS[a.arrival_day]}</td></tr>)}</tbody></table></section>}
 {tab==='locations'&&<section className="card"><table><thead><tr><th>חברה</th><th>מדף</th><th>קופסה</th></tr></thead><tbody>{locations.map(l=><tr key={l.id}><td>{companies.find(c=>c.id===l.company_id)?.name||'—'}</td><td>{l.shelf}</td><td>{l.box_name}</td></tr>)}</tbody></table></section>}</div>
}
